@url = http://localhost:{{$dotenv PORT}}
# @url = http://localhost:3000
@mainEndpoint = profil

# FAVORITES

### POST /profil/favorite
POST {{url}}/{{mainEndpoint}}/favorite
Content-Type: application/json

{
  "id": 12
}

### GET /profil/favorite
GET {{url}}/{{mainEndpoint}}/favorite

### DELETE /profil/favorite/:id
DELETE {{url}}/{{mainEndpoint}}/favorite/12


# ACTIVITIES

### GET /profil/activity
GET {{url}}/{{mainEndpoint}}/activity

### POST profil/activity
POST {{url}}/{{mainEndpoint}}/activity
Content-Type: application/json

{
  "title": "L'attraction 2000 & top",
  "description": "Une bonne attraction",
  "url": "blablooo",
  "image": "blabla",
  "address": "rue du PHP ",
  "phone": "0654748965",
  "longitude": 45.326359,
  "latitude": 12.25489,
  "city": "Lyon"
}







# {
#   "id": 1,
#   "title": "attraction 2000",
#   "slug": "attraction-2000-lyon-3",
#   "description": "Une bonne attraction",
#   "image": "blabla",
#   "address": "rue du PHP ",
#   "phone": "0654748965",
#   "longitude": 45.326359,
#   "latitude": 12.25489,
#   "city": "lyon"
# }
