# @url = http://localhost:{{$dotenv PORT}}
@url = http://localhost:3000
@mainEndpoint = activity

###
GET {{url}}/{{mainEndpoint}}/rating

###
GET {{url}}/{{mainEndpoint}}/recent

###
@country = France
@city = Aulnay-sous-bois
GET {{url}}/{{mainEndpoint}}/{{country}}/{{city}}


###
